## TO BUILD USE ==>  docker build -f DockerFile -t wintersoldier/burgerbuilder:latest .
## TO RUN USE ==>     docker run -d --name myburger -p 3000:3000 wintersoldier/burgerbuilder:latest
FROM ubuntu
MAINTAINER Winter Soldier <sagarksuchi@gmail.com>
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y sudo
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt-get install -y nodejs
RUN git clone https://github.com/suchiksagar/burgerbuilder.git /opt/downloads/burgerbuilder
RUN npm install /opt/downloads/burgerbuilder
ENTRYPOINT [ "/usr/bin/npm", "start", "--prefix",  "/opt/downloads/burgerbuilder"]
